### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by JTrotta** [FreakyAli/NFC-NDEF#5]
It seems projects are class library not app?

**Comment by FreakyAli** [comment]
I haven't tested this again since I wrote this blog, but until then it was working! Also not sure wdym by projects are class libraries because I'm able to run them fine! They seem to functional projects... Am I missing something here?

**Comment by lwdllc** [comment]
i am having issues running this project. it errors for both ios and android. xcode version: 15.0.1 and android api 33. i would really like to have this work! willing to pay you for your time in helping me get this running

**Comment by FreakyAli** [comment]
Sure let me check this and get back to you!

**Comment by lwdllc** [comment]
> Sure let me check this and get back to you!

thank you so much! i am only concerned with reading; not writing at the moment

**Comment by FreakyAli** [comment]
@lwdllc I have pushed a commit with an update to the latest .NET8 release which is probably why you were not able to build, let me know if this fixes your issue

**Comment by lwdllc** [comment]
you are awesome for responding so quickly! i was able to run the project yesterday but i need **scanning** to work on both ios and android. seems like your sample program is geared towards writing to the nfc card and that's it. can i pay you to add nfc scanning to the projects? it would be nice to simply pop the ndef payload up in a dialog or something. i should also reiterate the projects crash when using the following sdks: xcode version: 15.0.1 and android api 33

**Comment by FreakyAli** [comment]
@lwdllc did you try this with the latest version I added sometime ago? I have added a fix for that crash as well, please reach out to me over LinkedIn if possible!

**Comment by lwdllc** [comment]
> @lwdllc did you try this with the latest version I added sometime ago? I have added a fix for that crash as well, please reach out to me over LinkedIn if possible!

can we skype?

**Comment by FreakyAli** [comment]
I guess, reach out to me on my email I'll see what I can do

**Comment by lwdllc** [comment]
what's your email?

**Comment by FreakyAli** [comment]
hakimgulamali88@gmail.com(I will delete this once you send me an email I don't wanna make it public if possible so respond asap)

**Comment by FreakyAli** [comment]
Closing this since its working after some changes :)
